name: Dockerized Tests

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  all-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Run tests in docker container
        run:  make docker-test-all
