name: golangci-lint

on:
  push:
    tags: [ "v*" ]
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "**" ]

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19.7
      - uses: actions/checkout@v3
      - name: install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - name: run golangci-lint
        run: golangci-lint run
